steps:
- name: node:16.17.1
  entrypoint: 'yarn'
  args: ['install']
- name: node:16.17.1
  entrypoint: 'yarn'
  args: ['lint']
- name: node:16.17.1
  entrypoint: 'yarn'
  args: ['test']
- name: node:16.17.1
  entrypoint: 'yarn'
  args: ['build']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy --version=main']
timeout: '1600s'
