steps:
- name: 'bash'
  script: |
    #!/usr/bin/env bash
    apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
- name: node:16
  entrypoint: 'yarn'
  args: ['install']
- name: node:16
  entrypoint: 'yarn'
  args: ['lint']
- name: node:16
  entrypoint: 'yarn'
  args: ['test']
- name: node:16
  entrypoint: 'yarn'
  args: ['build']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy --version=main']
timeout: '1600s'
