---
name: Terraform checks

"on":
  pull_request:
    paths:
      - '.github/workflows/tf.workflow.yml'
      - 'tf/**'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/tf.workflow.yml'
      - 'tf/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
    run:
      working-directory: 'tf/'
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check -recursive

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
